const posts=[
{id:'start',title:'写博客，是给日常留一个位置',date:'2026-10-06',category:'生活随笔',tags:['记录','日常'],series:'写作这件事',lead:'不必每一次都有结论，也不必把每一个想法打磨得完美。先写下来，让那些微小的发现有处可去。',sections:[['从一个小问题开始','为什么想写博客？也许只是因为，有些事情当时觉得很清楚，过一阵子却只剩下模糊的印象。一本读到一半的书，一次绕远路的散步，或者终于弄明白的一个问题，都值得留下一点痕迹。'],['给不同的兴趣留白','这里可以同时放下技术笔记、生活随笔、读书片段和途中见闻。分类只是方便查找，不必成为写作的边界。今天对什么好奇，就从什么开始。'],['允许它保持未完成','写下来并不意味着定论。过去的想法可以被补充，也可以被推翻。把文章当作一个阶段的记录，反而能更诚实地表达当时的自己。']]},
{id:'tools',title:'把工具用简单，把注意力留给事情',date:'2026-10-04',category:'技术笔记',tags:['工具','效率'],series:'',lead:'一个小小的整理实验：留下真正会用到的工具，减少反复切换，也减少为了整理而整理。',sections:[['先观察，再调整','当一件事做起来不顺手，我会先看看自己在哪一步停住。是找不到资料，还是步骤太多？先记录具体的摩擦，比立即换一套工具更有帮助。'],['让默认选择少一点','为相同类型的事情保留一个固定入口：笔记放在同一个地方，正在做的任务保持简短，暂时不用的东西收起来。选择少一点，开始往往容易一点。'],['工具也需要退出机制','如果一个工具长期没有帮到实际工作，就可以暂时不用。好的流程不是拥有最多功能，而是能让我重新把注意力放回正在做的事情。']]},
{id:'reading',title:'读完一本书之后，我想留下什么',date:'2026-10-01',category:'阅读札记',tags:['阅读','笔记'],series:'',lead:'比起摘下很多句子，我更想记住：这本书让我重新看待了哪一件事。',sections:[['从摘抄到提问','读书的时候，有时会忍不住标记很多句子。但合上书后，最先浮现的往往不是其中某一段，而是一个还没有解决的问题。'],['只写下一个变化','我试着在笔记里只回答一个问题：读完之后，我的想法有什么变化？不求覆盖全书，也不要求总结得全面，只抓住与自己有关的那一点。'],['隔一段时间再回来','有些书在当下没有留下特别强烈的印象，却会在后来的一次经历中突然被想起。给笔记留出空白，也是给未来的理解留出位置。']]},
{id:'walk',title:'没有目的地的周末散步',date:'2026-09-27',category:'途中见闻',tags:['散步','日常'],series:'',lead:'关掉导航，在熟悉的街区多走一条小路。原来新鲜感有时候并不需要很远的距离。',sections:[['多走一条街','平时走路总想着快一点到达。周末试着换一条路，不急着转弯，也不急着判断这条路是不是最短。'],['注意那些小东西','路边店铺换了招牌，树影落在墙上，窗台上多了一盆植物。这些没有进入行程表的细节，构成了一次散步真正留下的印象。'],['把发现带回来','回到家后，只记下三件当天注意到的事情。不需要一篇完整游记，几句话就足够保存那一小段时间。']]},
{id:'small-notes',title:'从一段短笔记开始，而不是一篇长文章',date:'2026-09-22',category:'生活随笔',tags:['写作','记录'],series:'写作这件事',lead:'写不出来的时候，先把门槛放低。一段清楚的观察，也是一篇文章的起点。',sections:[['先完成一段','如果总是等到有完整的结构才开始，很多想法就会停留在脑海里。先描述一个场景或一个问题，之后再决定是否展开。'],['具体比漂亮重要','与其追求一个漂亮的开头，不如把事情说清楚：发生了什么，为什么注意到它，当时在想什么。'],['让笔记慢慢长大','短笔记不必立刻变成长文章。它可以保留原样，也可以在新的经历出现后被续写。写作的节奏可以由生活来决定。']]}
];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const url=(view,name)=>`/?view=${view}&name=${encodeURIComponent(name)}`;
const link=(view,name)=>`<a href="${url(view,name)}">${esc(name)}</a>`;
const main=document.querySelector('main');const params=new URLSearchParams(location.search);const view=params.get('view')||'home';const name=params.get('name')||'';
document.querySelector(`[data-nav="${['post','category','tag','series-detail'].includes(view)?({post:'home',category:'categories',tag:'tags','series-detail':'series'}[view]):view}"]`)?.classList.add('active');
const heading=(title,description)=>`<section class="intro"><div><p class="eyebrow">A PERSONAL JOURNAL</p><h1>${esc(title)}</h1><p>${esc(description)}</p></div><div class="issue">NOTES / 2026<br>保持好奇，慢慢记录。</div></section>`;
const categories=[...new Set(posts.map(p=>p.category))];const tags=[...new Set(posts.flatMap(p=>p.tags))];
const card=p=>`<article class="post"><div class="meta"><time datetime="${p.date}">${p.date.replaceAll('-',' / ')}</time>${link('category',p.category)}<span class="sample">示例文章</span></div><h2><a href="/?view=post&name=${p.id}">${esc(p.title)}</a></h2><p>${esc(p.lead)}</p><div class="post-end"><div class="tags">${p.tags.map(t=>`<a href="${url('tag',t)}"># ${esc(t)}</a>`).join('')}</div><a class="read" href="/?view=post&name=${p.id}">阅读全文</a></div></article>`;
const sidebar=()=>`<aside><div class="aside-block"><h2 class="aside-title">关于这里</h2><div class="monogram" aria-hidden="true">未</div><p>一个不限定主题的个人博客。记录学到的东西，也记录生活里值得停留的瞬间。</p><a class="read" href="/?view=about">更多关于这个博客</a></div><div class="aside-block"><h2 class="aside-title">按主题阅读</h2>${categories.map(c=>`<a class="side-link" href="${url('category',c)}">${c}<span>${posts.filter(p=>p.category===c).length}</span></a>`).join('')}</div><div class="aside-block"><h2 class="aside-title">系列</h2><a class="side-link" href="${url('series-detail','写作这件事')}">写作这件事<span>2 篇</span></a></div><div class="aside-block note"><p>当前文章为原创示例内容，展示博客的阅读效果。</p></div></aside>`;
const rows=list=>list.map(p=>`<div class="archive-row"><a href="/?view=post&name=${p.id}">${esc(p.title)}</a><time datetime="${p.date}">${p.date}</time></div>`).join('');
if(view==='home'){main.innerHTML=heading('随手写下，慢慢想明白。','技术、生活、书与路上遇见的一切。')+`<div class="layout"><section><div class="section-label"><span>最新文章</span><span>${posts.length} 篇示例</span></div>${posts.map(card).join('')}</section>${sidebar()}</div>`;}
else if(view==='post'){const p=posts.find(p=>p.id===name);if(p){document.title=`${p.title} · 未定稿`;document.querySelector('meta[name="description"]').content=p.lead;main.innerHTML=`<article class="article"><a class="back" href="/">返回文章列表</a><h1>${esc(p.title)}</h1><div class="meta"><time datetime="${p.date}">${p.date}</time>${link('category',p.category)}<span class="sample">示例文章</span></div><p class="lead">${esc(p.lead)}</p><div class="body">${p.sections.map(([h,b])=>`<h2>${esc(h)}</h2><p>${esc(b)}</p>`).join('')}</div><div class="article-tail"><div class="tags">${p.tags.map(t=>link('tag',t)).join('')}</div>${p.series?`<p>所属系列：${link('series-detail',p.series)}</p>`:''}<p class="meta">这是一篇原创示例文章，尚未替换为博主的实际内容。</p></div></article>`;}else{main.innerHTML=heading('没有找到这篇文章','你可以回到文章列表继续阅读。')+'<p><a class="read" href="/">返回首页</a></p>';}}
else if(view==='about'){main.innerHTML=heading('关于未定稿','给想法一个可以慢慢生长的地方。')+`<div class="about"><p>这里是一个个人博客，主题没有固定边界。技术、阅读、日常生活和途中见闻，都可以成为一篇文章的起点。</p><p>「未定稿」是这个博客暂时的名字。想法会变化，文章可以续写，不必等到所有事情都想清楚才开始记录。</p><p>目前还没有填写博主的个人介绍。这里可以换成你的名字、经历，以及你想与读者分享的故事。</p><p class="meta">本站现有文章均为原创示例内容。</p><a class="read" href="/">开始阅读</a></div>`;}
else if(view==='categories'){main.innerHTML=heading('分类','不同的兴趣，各自有个位置。')+`<div class="archive-list">${categories.map(c=>`<h2 class="group-title">${link('category',c)} <small class="meta">${posts.filter(p=>p.category===c).length} 篇</small></h2>${rows(posts.filter(p=>p.category===c))}`).join('')}</div>`;}
else if(view==='tags'){main.innerHTML=heading('标签','从一个词，找到相关的记录。')+`<div class="archive-list"><div class="tag-cloud">${tags.map(t=>`<a href="${url('tag',t)}">${esc(t)} · ${posts.filter(p=>p.tags.includes(t)).length}</a>`).join('')}</div></div>`;}
else if(view==='series'){main.innerHTML=heading('系列','把有关联的想法，接着写下去。')+`<div class="archive-list"><h2 class="group-title">${link('series-detail','写作这件事')}</h2>${rows(posts.filter(p=>p.series))}</div>`;}
else if(['category','tag','series-detail'].includes(view)){const list=posts.filter(p=>view==='category'?p.category===name:view==='tag'?p.tags.includes(name):p.series===name);main.innerHTML=heading(name||'文章归档',`${list.length} 篇示例文章`)+`<div class="archive-list">${list.map(card).join('')||'<p>这个主题下还没有文章。</p>'}</div>`;}
else{main.innerHTML=heading('页面未找到','可以从首页继续阅读。')+'<p><a href="/">返回首页</a></p>';}
if(view!=='home'&&view!=='post')document.title=`${({categories:'分类',tags:'标签',series:'系列',about:'关于'}[view])||name||'文章'} · 未定稿`;
